import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Privacy Policy · Morni", description: "How Morni collects, uses, stores and protects personal data." };

const sections = [
  { title: "1. Introduction", paragraphs: ["Welcome to Morni. This Privacy Policy explains how REAL MAGIC TRADING L.L.C. (\"Morni\", \"we\", \"us\" or \"our\") collects, uses, stores, discloses and protects your Personal Data when you access or use the Morni website, mobile application or other digital platforms through which Morni provides its services (collectively, the \"Platform\").", "Morni operates the Platform through which Customers may browse and purchase apparel and other Products offered by participating Vendors, with delivery services initially facilitated through independent third-party logistics providers. We respect your privacy and are committed to protecting your Personal Data in accordance with applicable laws of the United Arab Emirates, including Federal Decree-Law No. 45 of 2021 Concerning the Protection of Personal Data, as amended from time to time (\"UAE PDPL\"). By using the Platform, you acknowledge this Privacy Policy. Where consent is required by law, we will obtain it in the manner required."] },
  { title: "2. Who we are", paragraphs: ["REAL MAGIC TRADING L.L.C. · Trade Licence No. 1033733 · Commercial Register No. 598091 · Shop 2, Jan Ali Ali Bin Redha, Bur Dubai, Al Souq Al Kabeer, Dubai, United Arab Emirates."] },
  { title: "3. What Personal Data do we collect?", paragraphs: ["Depending on how you use the Platform, we may collect personal and account information; contact and delivery information; order and transaction information; payment status, method and related references; device and technical information; usage and interaction information; customer-support correspondence; and delivery location information where required for delivery or Platform functionality.", "Payment-card information is processed by the relevant third-party payment service provider under its applicable terms and privacy practices."] },
  { title: "4. How do we collect your Personal Data?", paragraphs: ["We collect Personal Data directly from you when you register, place an Order, make a payment, request a refund or return, contact support, submit reviews or feedback, participate in promotions or otherwise interact with the Platform; from Vendors, logistics providers, payment providers and other service providers; and automatically through cookies, log files, pixels, SDKs and similar technologies."] },
  { title: "5. How do we use your Personal Data?", paragraphs: ["We use Personal Data to create and manage accounts; process and fulfil Orders; facilitate payments and delivery; process returns and refunds; administer Morni Credits; provide support; operate, secure and improve the Platform; detect fraud and misuse; comply with legal and regulatory obligations; establish, exercise or defend legal claims; and, where permitted by law, send and measure promotional communications. You may opt out of promotional communications at any time."] },
  { title: "6. Legal basis for processing", paragraphs: ["Depending on the circumstances, Morni may process Personal Data on the basis of contractual necessity, legal or regulatory obligations, consent, legitimate interests where permitted by law, or establishment, exercise or defence of legal claims."] },
  { title: "7. Who do we share your Personal Data with?", paragraphs: ["We do not sell your Personal Data. Where necessary, we may share it with relevant Vendors; logistics and delivery providers; payment service providers; hosting, cloud, technology, customer-support, cybersecurity, analytics, communications and fraud-prevention providers; professional advisers; government and law-enforcement authorities where required or permitted; and parties involved in a permitted merger, acquisition, restructuring, financing or sale of assets."] },
  { title: "8. Third-party service providers", paragraphs: ["Where third parties process Personal Data on our behalf, we take reasonable steps to require authorised purposes, confidentiality and appropriate security and data-protection safeguards."] },
  { title: "9. Cookies and similar technologies", paragraphs: ["Morni may use cookies and similar technologies for essential functionality, preferences, account sessions, usage understanding, performance, fraud prevention and marketing where permitted. You may manage or disable cookies through your browser or device settings; disabling certain cookies may affect functionality. Where required, we will obtain appropriate consent before using non-essential cookies."] },
  { title: "10–12. Storage, security and breaches", paragraphs: ["We retain Personal Data for as long as reasonably necessary, or longer where required or permitted by law, taking account of accounts, contracts, legal, tax, accounting, dispute, fraud and security requirements. When no longer required, we take reasonable steps to delete, destroy or anonymise it.", "We maintain technical, organisational and administrative safeguards such as access controls, authentication, encryption, secure infrastructure, confidentiality obligations, monitoring, logging and incident response. No electronic transmission or storage method is completely secure. Morni maintains procedures for identifying, investigating and responding to Personal Data breaches and will notify authorities and/or affected Data Subjects where required by law."] },
  { title: "13–15. Your rights and marketing", paragraphs: ["Subject to applicable law and exemptions, you may have rights to information, access, correction, deletion, restriction or cessation of certain processing, transfer where applicable, withdrawal of consent and objection. Contact us to exercise a right; we may verify your identity and will respond within the period required by law. We may decline or limit a request where permitted or required.", "You may opt out of promotional communications using the unsubscribe option, communication preferences or by contacting us. Transactional and service-related messages may still be sent where necessary."] },
  { title: "16–18. Third parties, children and changes", paragraphs: ["Third-party websites, applications and services may have their own privacy policies, which we recommend reviewing. The Platform is intended for persons legally capable of entering contracts. Morni does not knowingly seek Personal Data from children where prohibited by law.", "We may update this Privacy Policy to reflect changes in the Platform, technology, processing, business or law. Updates will be published with a revised Last Updated and, where applicable, Effective Date; additional notice or consent will be provided where required."] },
  { title: "19. Contact us", paragraphs: ["REAL MAGIC TRADING L.L.C. · Trade Licence No. 1033733 · Commercial Register No. 598091 · Shop 2, Jan Ali Ali Bin Redha, Bur Dubai, Al Souq Al Kabeer, Dubai, United Arab Emirates · Email: mymorniuae@gmail.com · Customer Support: @morni_uae on Instagram."] },
  { title: "20. Governing law", paragraphs: ["This Privacy Policy is governed by the laws of the United Arab Emirates as applicable in the Emirate of Dubai, subject to mandatory requirements relating to Personal Data protection and privacy."] },
];

export default function PrivacyPage() { return <LegalDocument eyebrow="Morni legal" title="Privacy Policy" intro="This policy explains how Morni handles personal data when you use our Platform." updated="Last updated: 26 August 2026" sections={sections} />; }
