import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";

export const metadata: Metadata = { title: "Customer Terms & Conditions · Morni", description: "Terms governing use of Morni and purchases through the Platform." };

const sections = [
  { title: "1–3. About Morni, definitions and accounts", paragraphs: ["Morni is operated by REAL MAGIC TRADING L.L.C., Trade Licence No. 1033733, Commercial Register No. 598091, Shop 2, Jan Ali Ali Bin Redha, Bur Dubai, Al Souq Al Kabeer, Dubai, United Arab Emirates. Morni operates an online platform for products offered by participating Vendors and may use independent third-party logistics providers.", "Customer, Order, Product, Vendor, Try-Before-Accept and Morni Credits have the meanings given in these Terms. You must provide accurate information, protect your credentials, report unauthorised use and have legal capacity to enter binding contracts."] },
  { title: "4–6. Products, orders and cancellation", paragraphs: ["Review product name, size, colour, material, specifications, images, price and availability before ordering. Images are illustrative and colours may vary by device. Availability is subject to stock. Required product information, warnings and return conditions will be provided where required by law.", "You may place an Order through checkout. Product prices and applicable fees are shown before confirmation. Morni may cancel an affected Product or Order where stock, payment, product information, Vendor fulfilment, delivery or applicable law requires it. Any due refund is handled under these Terms and applicable law."] },
  { title: "7–8. Prices and payment", paragraphs: ["A Service Fee of AED 3 applies to applicable Orders and is displayed before confirmation. Delivery is free for Orders of AED 199 or more; otherwise the Delivery Fee is AED 7. Applicable taxes, including VAT, are charged under applicable law. The total payable is displayed before confirmation.", "Payment must be completed through an available payment method. Payments may be processed through third-party payment providers and the available methods and process are displayed at checkout."] },
  { title: "9–13. Try-Before-Accept, returns and product issues", paragraphs: ["For eligible apparel, Try-Before-Accept lets you inspect and, where appropriate, try on the Product at delivery. Check size and fit, colour, appearance, visible stains or damage and conformity with the Order. Decide while the rider is present; if you reject it, return it during the same interaction. After acceptance, ordinary change-of-mind, sizing, fit or colour returns are not available where the issue was reasonably identifiable at delivery, subject always to mandatory legal rights.", "Your first-ever return through Morni is free. After that, a Return Fee of AED 10 applies per Order involving a return, not per Product, and may be deducted where legally permitted. It will not restrict a mandatory consumer right.", "If a Product is damaged, defective, incorrect or materially misdescribed, notify the rider if apparent or contact Morni promptly if discovered later. Subject to verification and applicable law, remedies may include repair, replacement, return and refund or another legally required remedy. Handle Products reasonably and do not remove tags, alter or damage them during inspection or try-on."] },
  { title: "14. Refunds and Morni Credits", paragraphs: ["Where a refund is due, it is processed after the return or refund is confirmed, less applicable non-refundable fees where legally permissible. You may choose offered Morni Credits, credited immediately upon approval, or a refund to the original payment method or bank account, which may take up to twelve working days after Morni approves and initiates it. The AED 7 Delivery Fee, AED 3 Service Fee and applicable AED 10 Return Fee are non-refundable where legally permitted. Mandatory legal refund requirements prevail."] },
  { title: "15–16. Delivery and failed delivery", paragraphs: ["Delivery is available only in areas serviced by Morni. Estimated times are indicative and may vary due to traffic, weather, operations, stock, logistics or circumstances beyond reasonable control. Provide accurate delivery details and remain available; reasonable calls or messages from the rider may be required.", "A delivery may be treated as Failed Delivery if you are unavailable, cannot be contacted, refuse an accepted Order other than through Try-Before-Accept, or otherwise prevent completion. The rider may make four contact attempts and wait up to three hours. After two unsuccessful delivery attempts, the Order may be cancelled and returned to the Vendor; any refund follows Clause 14 and applicable law."] },
  { title: "17–19. Promotions, conduct and communications", paragraphs: ["Promotions, vouchers and codes may have additional displayed terms, eligibility, validity, usage limits and availability. Do not use the Platform unlawfully, provide misleading information, misuse returns or refunds, make fraudulent claims, damage Products, obtain unauthorised benefits, interfere with security, access systems without authorisation, introduce malicious code or impersonate others. Morni may take proportionate action subject to law.", "Morni may contact you by email, telephone, SMS, WhatsApp, in-app notifications or other available channels for transactional purposes. Promotional communications are sent in accordance with applicable law and consent requirements, and you may opt out."] },
  { title: "20–23. Privacy, third parties and availability", paragraphs: ["Morni processes personal data for accounts, Orders, payments, delivery, support, security and other lawful operational purposes in accordance with applicable UAE data-protection law. See the Morni Privacy Policy for details.", "Third-party payment, logistics, technology and other services may have their own terms and privacy policies. Morni will use reasonable efforts to maintain Platform availability, but it may be unavailable for maintenance, technical or operational reasons. Nothing limits a mandatory refund, compensation or consumer remedy."] },
  { title: "24–27. Complaints, accounts, records and changes", paragraphs: ["Submit complaints, refund requests and queries through Morni support channels. You may approach a competent consumer-protection or other authority where permitted. Morni may suspend or terminate accounts for fraud, material misuse, breach, unlawful conduct or legitimate security or operational reasons, subject to law.", "Morni will provide invoices or transaction records containing information required by applicable law, including product, transaction, price, tax and provider details and Arabic information where required. Terms may be updated; material amendments will be published with an effective date and notified or accepted where required. The Terms applicable to an Order are generally those in effect when placed, subject to mandatory law."] },
  { title: "28–30. Governing law, general provisions and contact", paragraphs: ["These Terms are governed by UAE law as applicable in Dubai. Subject to mandatory jurisdiction, Dubai courts have exclusive jurisdiction. Severability, no waiver, assignment and entire-agreement provisions apply, and no provision excludes mandatory statutory or regulatory rights.", "For questions, complaints, refund requests or assistance: REAL MAGIC TRADING L.L.C., Trade Licence No. 1033733, Shop 2, Jan Ali Ali Bin Redha, Bur Dubai, Al Souq Al Kabeer, Dubai, United Arab Emirates · mymorniuae@gmail.com · @morni_uae on Instagram · 058-6927273."] },
];

export default function TermsPage() { return <LegalDocument eyebrow="Morni legal" title="Customer Terms & Conditions" intro="These Terms govern access to Morni and purchases made through the Platform." updated="Last updated: 26 August 2026 · Effective date: 26 August 2026" sections={sections} />; }
